//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UEExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot import binary files with an unequal length!.
        /// </summary>
        internal static string CANNOT_IMPORT_BINARY_NOTEQUAL_LENGTH {
            get {
                return ResourceManager.GetString("CANNOT_IMPORT_BINARY_NOTEQUAL_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the package because of the following exception: {0}.
        /// </summary>
        internal static string COULDNT_SAVE_EXCEPTION {
            get {
                return ResourceManager.GetString("COULDNT_SAVE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send this report. Please try again later!.
        /// </summary>
        internal static string ExceptionDialog_FAIL {
            get {
                return ResourceManager.GetString("ExceptionDialog_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for reporting this exception occurrance!.
        /// </summary>
        internal static string ExceptionDialog_THANKS {
            get {
                return ResourceManager.GetString("ExceptionDialog_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name index .
        /// </summary>
        internal static string INVALID_NAME_INDEX {
            get {
                return ResourceManager.GetString("INVALID_NAME_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Object index .
        /// </summary>
        internal static string INVALID_OBJECT_INDEX {
            get {
                return ResourceManager.GetString("INVALID_OBJECT_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is .
        /// </summary>
        internal static string NAME_IS {
            get {
                return ResourceManager.GetString("NAME_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Object was found..
        /// </summary>
        internal static string NO_OBJECT_WAS_FOUND {
            get {
                return ResourceManager.GetString("NO_OBJECT_WAS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is .
        /// </summary>
        internal static string OBJECT_IS {
            get {
                return ResourceManager.GetString("OBJECT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Extractor.
        /// </summary>
        internal static string ProgramForm_Cache_Extractor {
            get {
                return ResourceManager.GetString("ProgramForm_Cache_Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to request the latest version. Please try again later!
        ///Exception:{0}.
        /// </summary>
        internal static string ProgramForm_checkForUpdates_Failed {
            get {
                return ResourceManager.GetString("ProgramForm_checkForUpdates_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version of {0}.
        /// </summary>
        internal static string ProgramForm_checkForUpdates_Latest_Version {
            get {
                return ResourceManager.GetString("ProgramForm_checkForUpdates_Latest-Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking yes will bring you to the page with the latest version!
        ///
        ///Your version: {0}
        ///Latest version: {1}.
        /// </summary>
        internal static string ProgramForm_checkForUpdates_New_Update {
            get {
                return ResourceManager.GetString("ProgramForm_checkForUpdates_New-Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        internal static string ProgramForm_checkForUpdates_New_Version {
            get {
                return ResourceManager.GetString("ProgramForm_checkForUpdates_New-Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string ProgramForm_checkForUpdates_Progress_Status {
            get {
                return ResourceManager.GetString("ProgramForm_checkForUpdates_Progress-Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading package: {0}.
        /// </summary>
        internal static string ProgramForm_LoadFile_Failed_loading_package {
            get {
                return ResourceManager.GetString("ProgramForm_LoadFile_Failed_loading_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file {0}....
        /// </summary>
        internal static string ProgramForm_LoadFile_Loading_file {
            get {
                return ResourceManager.GetString("ProgramForm_LoadFile_Loading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Natives Table Generator.
        /// </summary>
        internal static string ProgramForm_Unreal_Natives_Table_Generator {
            get {
                return ResourceManager.GetString("ProgramForm_Unreal_Natives_Table_Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this will edit your registry file. 
        ///If you happen to move the &quot;UE Explorer&quot; folder, uninstall or update it, then please disable this before doing so!.
        /// </summary>
        internal static string RegistryWarning {
            get {
                return ResourceManager.GetString("RegistryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string SAVE_QUESTION {
            get {
                return ResourceManager.GetString("SAVE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this? Warning! This change will be permanent, make sure you have made a backup!.
        /// </summary>
        internal static string SAVE_QUESTION_WARNING {
            get {
                return ResourceManager.GetString("SAVE_QUESTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to go the folder with the exported content?.
        /// </summary>
        internal static string UC_PackageExplorer_PerformNodeAction_QUESTIONEXPORTFOLDER {
            get {
                return ResourceManager.GetString("UC_PackageExplorer_PerformNodeAction_QUESTIONEXPORTFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UE_ProgramLogo {
            get {
                object obj = ResourceManager.GetObject("UE_ProgramLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
