//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UEExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutBox {
            get {
                object obj = ResourceManager.GetObject("AboutBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backwards {
            get {
                object obj = ResourceManager.GetObject("Backwards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string BinaryPage_BinaryPage_Binary_Title {
            get {
                return ResourceManager.GetString("BinaryPage_BinaryPage_Binary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinaryData: {0}.
        /// </summary>
        internal static string BinaryPage_SetNewObjectTarget_BinaryData___0_ {
            get {
                return ResourceManager.GetString("BinaryPage_SetNewObjectTarget_BinaryData___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot import binary files with an unequal length!.
        /// </summary>
        internal static string CANNOT_IMPORT_BINARY_NOTEQUAL_LENGTH {
            get {
                return ResourceManager.GetString("CANNOT_IMPORT_BINARY_NOTEQUAL_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to request the latest version. Please try again later!.
        /// </summary>
        internal static string CHECKFORUPDATES_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("CHECKFORUPDATES_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates(Current version is {0})....
        /// </summary>
        internal static string CHECKING_FOR_UPDATES_LOG {
            get {
                return ResourceManager.GetString("CHECKING_FOR_UPDATES_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} isn&apos;t supported.
        /// </summary>
        internal static string CLASS_ISNT_SUPPORTED {
            get {
                return ResourceManager.GetString("CLASS_ISNT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Code {
            get {
                object obj = ResourceManager.GetObject("Code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use Gildor&apos;s tool, try &quot;decompress.exe PACKAGENAME.EXT&quot; you may have to specify -lzo..
        /// </summary>
        internal static string COMPRESSED_HOWTO {
            get {
                return ResourceManager.GetString("COMPRESSED_HOWTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructing Objects....
        /// </summary>
        internal static string CONSTRUCTING_OBJECTS {
            get {
                return ResourceManager.GetString("CONSTRUCTING_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t reload due this error:
        ///
        ///	{0}.
        /// </summary>
        internal static string COULDNT_RELOAD_OBJECT {
            get {
                return ResourceManager.GetString("COULDNT_RELOAD_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the file because of the following exception: {0}.
        /// </summary>
        internal static string COULDNT_SAVE_EXCEPTION {
            get {
                return ResourceManager.GetString("COULDNT_SAVE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiler.
        /// </summary>
        internal static string DecompilerPage_DecompilerPage_Decompile_Title {
            get {
                return ResourceManager.GetString("DecompilerPage_DecompilerPage_Decompile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile: {0}.
        /// </summary>
        internal static string DecompilerPage_OnObjectTarget_Decompile___0_ {
            get {
                return ResourceManager.GetString("DecompilerPage_OnObjectTarget_Decompile___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing Objects....
        /// </summary>
        internal static string DESERIALIZING_OBJECTS {
            get {
                return ResourceManager.GetString("DESERIALIZING_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while exporting {0}
        ///{1}.
        /// </summary>
        internal static string EXCEPTION_OCCURRED_WHILE_EXPORTING {
            get {
                return ResourceManager.GetString("EXCEPTION_OCCURRED_WHILE_EXPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send this report. Please try again later!.
        /// </summary>
        internal static string ExceptionDialog_FAIL {
            get {
                return ResourceManager.GetString("ExceptionDialog_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for reporting this exception occurrance!.
        /// </summary>
        internal static string ExceptionDialog_THANKS {
            get {
                return ResourceManager.GetString("ExceptionDialog_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown by: {0}
        ///{1}{2}.
        /// </summary>
        internal static string ExceptionText {
            get {
                return ResourceManager.GetString("ExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportData {
            get {
                object obj = ResourceManager.GetObject("ExportData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported all packages content to {0}.
        ///
        ///Click Yes if you want to go to the output directory!.
        /// </summary>
        internal static string EXPORTED_ALL_PACKAGE_CLASSES {
            get {
                return ResourceManager.GetString("EXPORTED_ALL_PACKAGE_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting package {0}.
        /// </summary>
        internal static string EXPORTING_PACKAGE {
            get {
                return ResourceManager.GetString("EXPORTING_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportScript {
            get {
                object obj = ResourceManager.GetObject("ExportScript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Text.
        /// </summary>
        internal static string ExportTextTitle {
            get {
                return ResourceManager.GetString("ExportTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Results &quot;{0}&quot;.
        /// </summary>
        internal static string FIND_RESULTS_TITLE {
            get {
                return ResourceManager.GetString("FIND_RESULTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindDown {
            get {
                object obj = ResourceManager.GetObject("FindDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindInFile {
            get {
                object obj = ResourceManager.GetObject("FindInFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindNext {
            get {
                object obj = ResourceManager.GetObject("FindNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &quot;{0}&quot;.
        /// </summary>
        internal static string FindResultsPage_TextTitle___0__ {
            get {
                return ResourceManager.GetString("FindResultsPage_TextTitle___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forwards {
            get {
                object obj = ResourceManager.GetObject("Forwards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gildor.org/downloads.
        /// </summary>
        internal static string GildorDownloadsWebUrl {
            get {
                return ResourceManager.GetString("GildorDownloadsWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t acquire value.
        /// </summary>
        internal static string HexView_COULDNT_ACQUIRE_VALUE {
            get {
                return ResourceManager.GetString("HexView_COULDNT_ACQUIRE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string HexView_Offset {
            get {
                return ResourceManager.GetString("HexView_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0} + {1} ; 0x{2:x8}.
        /// </summary>
        internal static string HexView_Position {
            get {
                return ResourceManager.GetString("HexView_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string HexViewerForm_Title {
            get {
                return ResourceManager.GetString("HexViewerForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoTipInline_11_11 {
            get {
                object obj = ResourceManager.GetObject("InfoTipInline.11.11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking Objects....
        /// </summary>
        internal static string LINKING_OBJECTS {
            get {
                return ResourceManager.GetString("LINKING_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking yes will bring you to the page with the latest version!
        ///Installed version: {0}
        ///Latest version: {1}.
        /// </summary>
        internal static string NEW_VERSION_AVAILABLE_MESSAGE {
            get {
                return ResourceManager.GetString("NEW_VERSION_AVAILABLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        internal static string NEW_VERSION_AVAILABLE_TITLE {
            get {
                return ResourceManager.GetString("NEW_VERSION_AVAILABLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no results with the specified text &quot;{0}&quot;..
        /// </summary>
        internal static string NO_FIND_RESULTS {
            get {
                return ResourceManager.GetString("NO_FIND_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version of {0}.
        /// </summary>
        internal static string NO_NEW_VERSION_AVAILABLE_MESSAGE {
            get {
                return ResourceManager.GetString("NO_NEW_VERSION_AVAILABLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Object was found..
        /// </summary>
        internal static string NO_OBJECT_WAS_FOUND {
            get {
                return ResourceManager.GetString("NO_OBJECT_WAS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile.
        /// </summary>
        internal static string NodeItem_Decompile {
            get {
                return ResourceManager.GetString("NodeItem_Decompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As....
        /// </summary>
        internal static string NodeItem_ExportAs {
            get {
                return ResourceManager.GetString("NodeItem_ExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export with UE Model Viewer.
        /// </summary>
        internal static string NodeItem_ExportWithUEModelViewer {
            get {
                return ResourceManager.GetString("NodeItem_ExportWithUEModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in UE Model Viewer.
        /// </summary>
        internal static string NodeItem_OpenInUEModelViewer {
            get {
                return ResourceManager.GetString("NodeItem_OpenInUEModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afspelen.
        /// </summary>
        internal static string NodeItem_Play {
            get {
                return ResourceManager.GetString("NodeItem_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string NodeItem_View {
            get {
                return ResourceManager.GetString("NodeItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Binary Fields.
        /// </summary>
        internal static string NodeItem_ViewBinaryFields {
            get {
                return ResourceManager.GetString("NodeItem_ViewBinaryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Buffer....
        /// </summary>
        internal static string NodeItem_ViewBuffer {
            get {
                return ResourceManager.GetString("NodeItem_ViewBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Content....
        /// </summary>
        internal static string NodeItem_ViewContent {
            get {
                return ResourceManager.GetString("NodeItem_ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile Disassembled Tokens.
        /// </summary>
        internal static string NodeItem_ViewDisassembledTokens {
            get {
                return ResourceManager.GetString("NodeItem_ViewDisassembledTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Exception.
        /// </summary>
        internal static string NodeItem_ViewException {
            get {
                return ResourceManager.GetString("NodeItem_ViewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Table Buffer....
        /// </summary>
        internal static string NodeItem_ViewTableBuffer {
            get {
                return ResourceManager.GetString("NodeItem_ViewTableBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile Tokens.
        /// </summary>
        internal static string NodeItem_ViewTokens {
            get {
                return ResourceManager.GetString("NodeItem_ViewTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target found for &quot;View Buffer&quot;.
        /// </summary>
        internal static string NoTargetForViewBuffer {
            get {
                return ResourceManager.GetString("NoTargetForViewBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string NOTICE_TITLE {
            get {
                return ResourceManager.GetString("NOTICE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is {0}.
        /// </summary>
        internal static string OBJECT_IS {
            get {
                return ResourceManager.GetString("OBJECT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenfileDialog {
            get {
                object obj = ResourceManager.GetObject("OpenfileDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Package {
            get {
                object obj = ResourceManager.GetObject("Package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package successfully exported to {0}.
        /// </summary>
        internal static string PACKAGE_EXPORTED_TO {
            get {
                return ResourceManager.GetString("PACKAGE_EXPORTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package is compressed! Compressed packages are not supported.
        ///
        ///Please consider decompressing the package using &quot;Unreal Package Decompressor&quot; from Gildor
        ///
        ///You can download the tool from http://www.gildor.org/downloads or press OK to go there now..
        /// </summary>
        internal static string PACKAGE_IS_COMPRESSED {
            get {
                return ResourceManager.GetString("PACKAGE_IS_COMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Package....
        /// </summary>
        internal static string PACKAGE_LOADING {
            get {
                return ResourceManager.GetString("PACKAGE_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package&apos;s MetaInfo.
        /// </summary>
        internal static string PACKAGE_METAINFO {
            get {
                return ResourceManager.GetString("PACKAGE_METAINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package has an unknown signature.
        ///
        ///Are you sure you want to try to deserialize this package? Clicking Yes might lead to unexpected results!.
        /// </summary>
        internal static string PACKAGE_UNKNOWN_SIGNATURE {
            get {
                return ResourceManager.GetString("PACKAGE_UNKNOWN_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Explorer.
        /// </summary>
        internal static string PackageExplorerPage_PackageExplorerPage_Package_Explorer_Title {
            get {
                return ResourceManager.GetString("PackageExplorerPage_PackageExplorerPage_Package_Explorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pin {
            get {
                object obj = ResourceManager.GetObject("Pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to {0} is not configured. Select the program&apos;s executable!.
        /// </summary>
        internal static string PLEASE_SELECT_PATH {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Extractor.
        /// </summary>
        internal static string ProgramForm_Cache_Extractor {
            get {
                return ResourceManager.GetString("ProgramForm_Cache_Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string ProgramForm_Check_for_Updates_Status {
            get {
                return ResourceManager.GetString("ProgramForm_Check_for_Updates_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading package: {0}.
        /// </summary>
        internal static string ProgramForm_LoadFile_Failed_loading_package {
            get {
                return ResourceManager.GetString("ProgramForm_LoadFile_Failed_loading_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file {0}....
        /// </summary>
        internal static string ProgramForm_LoadFile_Loading_file {
            get {
                return ResourceManager.GetString("ProgramForm_LoadFile_Loading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Natives Table Generator.
        /// </summary>
        internal static string ProgramForm_Unreal_Natives_Table_Generator {
            get {
                return ResourceManager.GetString("ProgramForm_Unreal_Natives_Table_Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this will edit your registry file. 
        ///If you happen to move the &quot;UE Explorer&quot; folder, uninstall or update it, then please disable this before doing so!.
        /// </summary>
        internal static string RegistryWarning {
            get {
                return ResourceManager.GetString("RegistryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string SAVE_QUESTION {
            get {
                return ResourceManager.GetString("SAVE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this? Warning! This change will be permanent, make sure you have made a backup!.
        /// </summary>
        internal static string SAVE_QUESTION_WARNING {
            get {
                return ResourceManager.GetString("SAVE_QUESTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved!.
        /// </summary>
        internal static string SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        internal static string SAVED {
            get {
                return ResourceManager.GetString("SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search as Object.
        /// </summary>
        internal static string SEARCH_AS_OBJECT {
            get {
                return ResourceManager.GetString("SEARCH_AS_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the UnrealWiki for &quot;{0}&quot;.
        /// </summary>
        internal static string SEARCH_WIKI_ITEM {
            get {
                return ResourceManager.GetString("SEARCH_WIKI_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching classes....
        /// </summary>
        internal static string SEARCHING_CLASSES_STATUS {
            get {
                return ResourceManager.GetString("SEARCHING_CLASSES_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist!.
        /// </summary>
        internal static string THING_DOESNT_EXIST {
            get {
                return ResourceManager.GetString("THING_DOESNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to go the folder with the exported content?.
        /// </summary>
        internal static string UC_PackageExplorer_PerformNodeAction_QUESTIONEXPORTFOLDER {
            get {
                return ResourceManager.GetString("UC_PackageExplorer_PerformNodeAction_QUESTIONEXPORTFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UE_ProgramLogo {
            get {
                object obj = ResourceManager.GetObject("UE_ProgramLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/UE.Explorer.
        /// </summary>
        internal static string UEExplorerFacebookUrl {
            get {
                return ResourceManager.GetString("UEExplorerFacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/UE-Explorer/UE-Explorer/issues.
        /// </summary>
        internal static string UEExplorerIssuesUrl {
            get {
                return ResourceManager.GetString("UEExplorerIssuesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Class.
        /// </summary>
        internal static string UnrealClassFilter {
            get {
                return ResourceManager.GetString("UnrealClassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized commandline option {0}.
        /// </summary>
        internal static string UNRECOGNIZED_COMMANDLINE_OPTION {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_COMMANDLINE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized export type {0}.
        /// </summary>
        internal static string UNRECOGNIZED_EXPORT_TYPE {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_EXPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.beyondunreal.com/?ns0=1&amp;ns100=1&amp;ns102=1&amp;ns104=1&amp;ns106=1&amp;search={0}&amp;title=Special%3ASearch&amp;fulltext=Advanced+search&amp;fulltext=Advanced+search.
        /// </summary>
        internal static string URL_UnrealWikiSearch {
            get {
                return ResourceManager.GetString("URL_UnrealWikiSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave: {0}.
        /// </summary>
        internal static string WavePlayerPage_OnObjectTarget_WavePlayer___0_ {
            get {
                return ResourceManager.GetString("WavePlayerPage_OnObjectTarget_WavePlayer___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Player.
        /// </summary>
        internal static string WavePlayerPage_WavePlayerPage_WavePlayer_Title {
            get {
                return ResourceManager.GetString("WavePlayerPage_WavePlayerPage_WavePlayer_Title", resourceCulture);
            }
        }
    }
}
